let gallery = [
	{ src: 'contents/image23.jpg' },
	{ src: 'contents/image22.jpg' },
	{ src: 'contents/image21.jpg' },
	{ src: 'contents/image20.mp4' },
	{ src: 'contents/image19.jpg' },
	{ src: 'contents/image18.jpg', link: 'https://s24egao.github.io/motion' },
	{ src: 'contents/image17.jpg' },
	{ src: 'contents/image16.jpg' },
	{ src: 'contents/image15.jpg' },
	{ src: 'contents/image14.jpg' },
	{ src: 'contents/image13.jpg' },
	{ src: 'contents/image12.jpg' },
	{ src: 'contents/image11.jpg', link: 'https://s24egao.github.io/3d' },
	{ src: 'contents/image10.jpg' },
	{ src: 'contents/image9.jpg' },
	{ src: 'contents/image8.jpg', link: 'https://openprocessing.org/sketch/1508210' },
	{ src: 'contents/image7.jpg', link: 'https://openprocessing.org/sketch/1500383' },
	{ src: 'contents/image6.jpg', },
	{ src: 'contents/image5.jpg', link: 'https://youtu.be/hsAqRQ134vI' },
	{ src: 'contents/image4.jpg' },
	{ src: 'contents/image3.jpg' },
	{ src: 'contents/image2.jpg' },
	{ src: 'contents/image1.jpg' },
]